version: '3'
services:
  server:
    image: server:latest
    build: ./app/server
    container_name: server
    volumes:
        - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  web:
    image: web:latest
    build: ./app/client
    container_name: web
    ports:
      - 8081:8080

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/mysql

  nginx:
    image: nginx
    build: app/nginx
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - server
      - web

volumes:
  data: