version: '3.5'
services:
  server:
    image: server:latest
    build: ./server
    container_name: server
    env_file: 
      - '.env'
    ports:
      - 5000:5000
    links:
      - db

  web:
    image: web:latest
    build: ./client
    container_name: web
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  data:
    container_name: data
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  db:
    container_name: db
    restart: always
    build: ./db
    ports:
      - 5454:5432
    volumes: 
      - data
    environment:
      POSTGRES_DB: mindful_db
      POSTGRES_USER: mindful
      POSTGRES_PASSWORD: secret-passkey

  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - server
      - web